# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-03 02:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('featreq', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientinfo',
            name='con_mail',
            field=models.EmailField(blank=True, default='', max_length=254, verbose_name='Contact email'),
        ),
        migrations.AlterField(
            model_name='clientinfo',
            name='con_name',
            field=models.CharField(blank=True, default='', max_length=64, verbose_name='Contact name'),
        ),
        migrations.AlterField(
            model_name='closedreq',
            name='date_tgt',
            field=models.DateField(blank=True, default=None, null=True, verbose_name='Target date'),
        ),
        migrations.AlterField(
            model_name='closedreq',
            name='priority',
            field=models.SmallIntegerField(blank=True, default=None, null=True, verbose_name='Priority'),
        ),
        migrations.AlterField(
            model_name='closedreq',
            name='reason',
            field=models.CharField(blank=True, default='', max_length=128, verbose_name='Details'),
        ),
        migrations.AlterField(
            model_name='featurereq',
            name='ref_url',
            field=models.URLField(blank=True, default='', max_length=254, verbose_name='Reference URL'),
        ),
        migrations.AlterField(
            model_name='openreq',
            name='date_tgt',
            field=models.DateField(blank=True, default=None, null=True, verbose_name='Target date'),
        ),
        migrations.AlterField(
            model_name='openreq',
            name='priority',
            field=models.SmallIntegerField(blank=True, default=None, null=True, unique=True, verbose_name='Priority'),
        ),
    ]
