# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-03 05:00
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('featreq', '0002_auto_20160403_0254'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='clientinfo',
            options={'verbose_name': 'client', 'verbose_name_plural': 'clients'},
        ),
        migrations.AlterModelOptions(
            name='closedreq',
            options={'verbose_name': 'closed request', 'verbose_name_plural': 'closed requests'},
        ),
        migrations.AlterModelOptions(
            name='featurereq',
            options={'verbose_name': 'request', 'verbose_name_plural': 'requests'},
        ),
        migrations.AlterModelOptions(
            name='openreq',
            options={'verbose_name': 'open request', 'verbose_name_plural': 'open requests'},
        ),
        migrations.AlterField(
            model_name='closedreq',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='closed_reqs', to='featreq.ClientInfo', verbose_name='Client'),
        ),
        migrations.AlterField(
            model_name='closedreq',
            name='req',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='closed_reqs', to='featreq.FeatureReq', verbose_name='Feature'),
        ),
        migrations.AlterField(
            model_name='openreq',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='open_reqs', to='featreq.ClientInfo', verbose_name='Client'),
        ),
        migrations.AlterField(
            model_name='openreq',
            name='req',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='open_reqs', to='featreq.FeatureReq', verbose_name='Feature'),
        ),
    ]
