# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-03 05:04
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('featreq', '0003_auto_20160403_0500'),
    ]

    operations = [
        migrations.AlterField(
            model_name='closedreq',
            name='req',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='closed_reqs', to='featreq.FeatureReq', verbose_name='Request'),
        ),
        migrations.AlterField(
            model_name='openreq',
            name='req',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='open_reqs', to='featreq.FeatureReq', verbose_name='Request'),
        ),
    ]
