# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-03 05:05
from __future__ import unicode_literals

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('featreq', '0004_auto_20160403_0504'),
    ]

    operations = [
        migrations.AlterField(
            model_name='featurereq',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='Request ID'),
        ),
    ]
