# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-04 00:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('featreq', '0005_auto_20160403_0505'),
    ]

    operations = [
        migrations.AlterField(
            model_name='openreq',
            name='date_tgt',
            field=models.DateTimeField(blank=True, default=None, null=True, verbose_name='Target date'),
        ),
    ]
