# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-04 01:18
from __future__ import unicode_literals

from django.db import migrations, models
import featreq.models


class Migration(migrations.Migration):

    dependencies = [
        ('featreq', '0006_auto_20160404_0015'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientinfo',
            name='date_add',
            field=models.DateTimeField(blank=True, default=featreq.models.approxnow, editable=False, verbose_name='Date added'),
        ),
        migrations.AlterField(
            model_name='closedreq',
            name='closed_at',
            field=models.DateTimeField(blank=True, db_index=True, default=featreq.models.approxnow, editable=False, verbose_name='Closed at'),
        ),
        migrations.AlterField(
            model_name='featurereq',
            name='date_cr',
            field=models.DateTimeField(blank=True, db_index=True, default=featreq.models.approxnow, editable=False, verbose_name='Created at'),
        ),
        migrations.AlterField(
            model_name='featurereq',
            name='date_up',
            field=models.DateTimeField(blank=True, default=featreq.models.approxnow, editable=False, verbose_name='Updated at'),
        ),
        migrations.AlterField(
            model_name='openreq',
            name='opened_at',
            field=models.DateTimeField(blank=True, db_index=True, default=featreq.models.approxnow, editable=False, verbose_name='Opened at'),
        ),
    ]
