# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-04 02:25
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('featreq', '0007_auto_20160404_0118'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientinfo',
            name='closedreqs',
            field=models.ManyToManyField(related_name='closedclients', through='featreq.ClosedReq', to='featreq.FeatureReq'),
        ),
        migrations.AlterField(
            model_name='clientinfo',
            name='openreqs',
            field=models.ManyToManyField(related_name='openclients', through='featreq.OpenReq', to='featreq.FeatureReq'),
        ),
        migrations.AlterField(
            model_name='closedreq',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='closedlist', to='featreq.ClientInfo', verbose_name='Client'),
        ),
        migrations.AlterField(
            model_name='closedreq',
            name='req',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='closedlist', to='featreq.FeatureReq', verbose_name='Request'),
        ),
        migrations.AlterField(
            model_name='openreq',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='openlist', to='featreq.ClientInfo', verbose_name='Client'),
        ),
        migrations.AlterField(
            model_name='openreq',
            name='req',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='openlist', to='featreq.FeatureReq', verbose_name='Request'),
        ),
    ]
