# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-05 05:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('featreq', '0009_auto_20160404_1638'),
    ]

    operations = [
        migrations.AlterField(
            model_name='closedreq',
            name='status',
            field=models.CharField(choices=[('', 'Select status'), ('C', 'Complete'), ('R', 'Rejected'), ('D', 'Deferred')], default='C', max_length=1, verbose_name='Closed as'),
        ),
        migrations.AlterField(
            model_name='featurereq',
            name='prod_area',
            field=models.CharField(choices=[('', 'Select area'), ('PO', 'Policies'), ('BI', 'Billing'), ('CL', 'Claims'), ('RE', 'Reports')], max_length=2, verbose_name='Product area'),
        ),
    ]
