# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-07 03:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('featreq', '0010_auto_20160405_0508'),
    ]

    operations = [
        migrations.AlterField(
            model_name='openreq',
            name='priority',
            field=models.SmallIntegerField(blank=True, default=None, null=True, verbose_name='Priority'),
        ),
        migrations.AlterUniqueTogether(
            name='closedreq',
            unique_together=set([('client', 'req')]),
        ),
        migrations.AlterUniqueTogether(
            name='openreq',
            unique_together=set([('client', 'req')]),
        ),
        migrations.AlterIndexTogether(
            name='openreq',
            index_together=set([('client', 'priority')]),
        ),
    ]
