# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-07 20:21
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('featreq', '0011_auto_20160407_0303'),
    ]

    operations = [
        migrations.AlterField(
            model_name='closedreq',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='closed_list', to='featreq.ClientInfo', verbose_name='Client'),
        ),
        migrations.AlterField(
            model_name='closedreq',
            name='req',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='closed_list', to='featreq.FeatureReq', verbose_name='Request'),
        ),
        migrations.AlterField(
            model_name='openreq',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='open_list', to='featreq.ClientInfo', verbose_name='Client'),
        ),
        migrations.AlterField(
            model_name='openreq',
            name='req',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='open_list', to='featreq.FeatureReq', verbose_name='Request'),
        ),
    ]
